spring:
  application:
    name: study-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGANCYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
